name: codecov
version: 2.0.0
description: Generates lcov and/or HTML coverage reports for Dart projects. (UNIX only)
homepage: https://github.com/codecov/dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  logging: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.0.0
  test: ^1.17.0

executables:
  codecov:
  generate_coverage:
